### ISSUE TITLE
Grafana 5.0.3 Users passwords being set and datasources created on every puppet run

### ISSUE THREAD

**Issue by ixaustralia** [voxpupuli/puppet-grafana#104]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.1
- Ruby: 2.3.1
- Distribution:
- Module version: 4.2.0
- Grafana 5.0.3

## How to reproduce (e.g Puppet code you use)
Create a datasource or user by any supported method.

## What are you seeing
On every puppet agent run, every datasource is re-created and passwords for users are being re-set (instance method is returning an empty string).

## What behaviour did you expect instead
Datasources are created once if they don't already exist. Users are created and hashes checked??

## Output log
```
Notice: /Stage[main]/Profile::Grafana/Grafana_user[tardoe]/password: password changed '' to 'p4dummypassword'
Notice: /Stage[main]/Profile::Grafana/Grafana_datasource[Influx]/ensure: created
Notice: /Stage[main]/Profile::Grafana/Grafana_datasource[Influx Public]/ensure: created
Notice: Applied catalog in 7.67 seconds
```

**Comment by aptituz** [comment]
I can't confirm the bug with the datasources, but I can confirm that behavior for users.

Given that the API doesn't support to "get" the password for a user and the fact that providers in puppet need to know the value to compare it, I think there is no "proper" solution to fix this problem.

A possible option would be to set passwords only for new users and ignore the password attribute when updating existing users. This would require to sacrifice the ability to change passwords via puppet, but maybe that's the better option instead of changing it on every puppet run and therefore issuing useless API requests.

**Comment by joernott** [comment]
A simple solution to check a password is using it, e.g. an api call to log in. I have used this kind of behaviour a couple of times. With a successful login, you can validate if the password is set correctly.
